/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panels;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import views.ApplicationView;

/**
 *
 * @author gioele.cavallo
 */
public class GamePanel extends javax.swing.JPanel {

    private final ApplicationView JFRAME;
    private int countImg = 0;

    /**
     * Creates new form GamePanel
     */
    public GamePanel(ApplicationView jFrame) {
        this.JFRAME = jFrame;
        //this.JFRAME.client.sendPacket("join "+this.JFRAME.client.getPlayer().getToken());
        initComponents();
        if(this.JFRAME.client.getPlayer() != null){
            this.tokenLabel.setText("token: " + this.JFRAME.client.getPlayer().getToken());
        }else{
            this.JFRAME.changePanel(new HomePanel(this.JFRAME));
        }
        ArrayList<String> arr = this.JFRAME.client.getPlayers();
        if(arr != null){
            String[] plrs = new String[arr.size()];
            for (int i = 0; i < plrs.length; i++) {
                plrs[i] = arr.get(i);
            }
            playerList.setListData(plrs);
        }else{
            playerList.setListData(new String[]{""});
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        playersLabel = new javax.swing.JLabel();
        IMG = new javax.swing.JButton();
        QuitGame = new javax.swing.JButton();
        HiddenWord = new javax.swing.JLabel();
        letterInput = new javax.swing.JTextField();
        letterLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        tokenLabel = new javax.swing.JLabel();

        playerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(playerList);

        playersLabel.setText("Players:");

        IMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMGActionPerformed(evt);
            }
        });

        QuitGame.setText("Quit game");
        QuitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitGameActionPerformed(evt);
            }
        });

        HiddenWord.setText("_ _ _ _ _ _ _");

        letterInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterInputActionPerformed(evt);
            }
        });

        letterLabel.setText("Lettera:");

        chatArea.setColumns(20);
        chatArea.setRows(5);
        chatArea.setText("\n");
        jScrollPane1.setViewportView(chatArea);

        tokenLabel.setText("token:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(playersLabel)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuitGame)
                        .addGap(60, 60, 60)
                        .addComponent(tokenLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letterLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HiddenWord, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(letterInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuitGame)
                    .addComponent(tokenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playersLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(HiddenWord)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(letterLabel)
                            .addComponent(letterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IMGActionPerformed

    private void QuitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitGameActionPerformed
        this.JFRAME.client.sendPacket(letterInput.getText());
        try {
            Thread.sleep(250);
            /*this.countImg = (this.countImg == 11) ? 0 : this.countImg++;
            Icon icon = new ImageIcon("src/resources/man_" + this.countImg++ + ".png");
            this.IMG.setIcon(icon);*/
        } catch (InterruptedException ex) {
            Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_QuitGameActionPerformed

    private void letterInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterInputActionPerformed
   
    public void refreshTable(){
        ArrayList<String> arr = this.JFRAME.client.getPlayers();
        if(arr != null){
            String[] plrs = new String[arr.size()];
            for (int i = 0; i < plrs.length; i++) {
                plrs[i] = arr.get(i);
            }
            playerList.setListData(plrs);
        }else{
            playerList.setListData(new String[]{""});
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HiddenWord;
    private javax.swing.JButton IMG;
    private javax.swing.JButton QuitGame;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField letterInput;
    private javax.swing.JLabel letterLabel;
    private javax.swing.JList<String> playerList;
    private javax.swing.JLabel playersLabel;
    private javax.swing.JLabel tokenLabel;
    // End of variables declaration//GEN-END:variables
}
