/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panels;

import game.Player;
import exceptions.*;
import game.Client;
import java.util.logging.Level;
import java.util.logging.Logger;
import views.ApplicationView;

/**
 *
 * @author gioele.cavallo
 */
public class HomePanel extends javax.swing.JPanel {

    private final ApplicationView JFRAME;

    /**
     * Creates new form HomePanel
     */
    public HomePanel(ApplicationView jFrame) {
        this.JFRAME = jFrame;
        initComponents();
        this.usedNameErr.setVisible(false);
        this.invalidNameErr.setVisible(false);
        this.tokenErr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinGameBt = new javax.swing.JButton();
        createGameBt = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        tokenInput = new javax.swing.JTextField();
        invalidNameErr = new javax.swing.JLabel();
        usedNameErr = new javax.swing.JLabel();
        settingsBt = new javax.swing.JButton();
        usernameInput = new javax.swing.JTextField();
        tokenErr = new javax.swing.JLabel();

        joinGameBt.setText("Join");
        joinGameBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGameBtActionPerformed(evt);
            }
        });

        createGameBt.setText("Create");
        createGameBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGameBtActionPerformed(evt);
            }
        });

        usernameLabel.setText("username:");

        tokenInput.setText("type the token");
        tokenInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenInputActionPerformed(evt);
            }
        });

        invalidNameErr.setForeground(new java.awt.Color(255, 80, 80));
        invalidNameErr.setText("Invalid name");
        invalidNameErr.setName(""); // NOI18N

        usedNameErr.setForeground(new java.awt.Color(255, 80, 80));
        usedNameErr.setText("name already used");

        settingsBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings.png"))); // NOI18N
        settingsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtActionPerformed(evt);
            }
        });

        usernameInput.setText("type your name");
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });

        tokenErr.setForeground(new java.awt.Color(255, 80, 80));
        tokenErr.setText("This token doesn't exist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(settingsBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usedNameErr))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(87, Short.MAX_VALUE)
                        .addComponent(createGameBt)
                        .addGap(82, 82, 82)
                        .addComponent(joinGameBt)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(invalidNameErr))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tokenInput, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tokenErr)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidNameErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usedNameErr)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGameBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinGameBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tokenInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tokenErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsBt)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinGameBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGameBtActionPerformed
        String token = tokenInput.getText();
        if (checkName()) {
            this.JFRAME.client.sendPacket("join " + token);
            try {
                Thread.sleep(250);
            } catch (InterruptedException ex) {}
            if (this.JFRAME.client.getError() != null ){
                if(this.JFRAME.client.getError().equals("token not valid")){
                    this.tokenErr.setVisible(true);
                }
            } else {
                this.JFRAME.changePanel(new GamePanel(this.JFRAME));
            }
        }
    }//GEN-LAST:event_joinGameBtActionPerformed

    private boolean checkName() {

        String name = usernameInput.getText();
        try {
            //this.JFRAME.client.startConnection(new Player(name));
            this.JFRAME.player = new Player(name);
            invalidNameErr.setVisible(false);
        } catch (InvalidNameException ine) {
            invalidNameErr.setVisible(true);
            return false;
        }

        this.JFRAME.client = new Client(this.JFRAME.player, this.JFRAME);

        try {
            Thread.sleep(150);
        } catch (InterruptedException ex) {
            Logger.getLogger(HomePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (this.JFRAME.client.getError() != null) {
            System.out.println("innnnn");
            if (this.JFRAME.client.getError().equals("used")) {
                usedNameErr.setVisible(true);
                return false;
            } else {
                usedNameErr.setVisible(false);
            }
        }
        return true;
    }

    private void createGameBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGameBtActionPerformed
        //this.JFRAME.client.sendPacket("name");
        //System.out.println(this.JFRAME.client.getName());
        if (checkName()) {
            System.out.println("nams is okay");
            this.JFRAME.changePanel(new CreateGamePanel(this.JFRAME));
        }
    }//GEN-LAST:event_createGameBtActionPerformed

    private void tokenInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokenInputActionPerformed

    private void settingsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtActionPerformed
        this.JFRAME.changePanel(new SettingsPanel(this.JFRAME));
    }//GEN-LAST:event_settingsBtActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createGameBt;
    private javax.swing.JLabel invalidNameErr;
    private javax.swing.JButton joinGameBt;
    private javax.swing.JButton settingsBt;
    private javax.swing.JLabel tokenErr;
    private javax.swing.JTextField tokenInput;
    private javax.swing.JLabel usedNameErr;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
