/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panels;
import game.Player;
import exceptions.*;
import java.io.IOException;
import views.ApplicationView;

/**
 *
 * @author gioele.cavallo
 */
public class HomePanel extends javax.swing.JPanel {

    private final ApplicationView JFRAME;

    /**
     * Creates new form HomePanel
     */
    public HomePanel(ApplicationView jFrame) {
        this.JFRAME = jFrame;
        initComponents();
        this.usedNameErr.setVisible(false);
        this.invalidNameErr.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinGameBt = new javax.swing.JButton();
        createGameBt = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        invalidNameErr = new javax.swing.JLabel();
        usedNameErr = new javax.swing.JLabel();
        settingsBt = new javax.swing.JButton();

        joinGameBt.setText("Join");
        joinGameBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGameBtActionPerformed(evt);
            }
        });

        createGameBt.setText("Create");
        createGameBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGameBtActionPerformed(evt);
            }
        });

        usernameLabel.setText("username:");

        usernameInput.setText("type your name");
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });

        invalidNameErr.setForeground(new java.awt.Color(255, 80, 80));
        invalidNameErr.setText("Invalid name");
        invalidNameErr.setName(""); // NOI18N

        usedNameErr.setForeground(new java.awt.Color(255, 80, 80));
        usedNameErr.setText("name already used");

        settingsBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings.png"))); // NOI18N
        settingsBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usedNameErr))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createGameBt)
                                .addGap(82, 82, 82)
                                .addComponent(joinGameBt)
                                .addGap(0, 81, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(usernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(invalidNameErr)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(settingsBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalidNameErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usedNameErr)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGameBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinGameBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(settingsBt)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinGameBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGameBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinGameBtActionPerformed

    private void createGameBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGameBtActionPerformed
        //System.out.println(this.JFRAME.client.getName());
        String name = usernameInput.getText();
        try {

            this.JFRAME.client.startConnection(new Player(name));

            this.JFRAME.player = new Player(name);
            this.JFRAME.changePanel(new CreateGamePanel(this.JFRAME));
        } catch (InvalidNameException ine) {
            usedNameErr.setVisible(true);
        } catch(IOException ioe){
            System.out.println("IOEXCEPTION");
        }
        /*boolean isRight = true;
        if (Helper.isValid(name)) {
            ArrayList<Player> arr = DateServer.getPlayers();
            for (int i = 0; i < arr.size(); i++) {
                if (arr.get(i).getName().equals(name)) {
                    usedNameErr.setVisible(true);
                    isRight = false;
                }
            }

        } else {
            invalidNameErr.setVisible(true);
            isRight = false;
        }*/
        //if (isRight) {
        // this.JFRAME.changePanel(new CreateGamePanel(this.JFRAME));
        /* //crea il giocatore ed inizia la partita
            Player plr = new Player(name);
            DateServer.addPlayer(plr);
            int[] values = new int[]{this.getX(),this.getY()};
            this.dispose();
            CreateGameView.startView(values);
        }*/
    }//GEN-LAST:event_createGameBtActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void settingsBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtActionPerformed
       this.JFRAME.changePanel(new SettingsPanel(this.JFRAME));
    }//GEN-LAST:event_settingsBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createGameBt;
    private javax.swing.JLabel invalidNameErr;
    private javax.swing.JButton joinGameBt;
    private javax.swing.JButton settingsBt;
    private javax.swing.JLabel usedNameErr;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
