/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import game.Client;
import game.DateServer;
import game.Player;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import views.panels.*;
import views.panels.HomePanel;

/**
 *
 * @author gioele.cavallo
 */
public class ApplicationView extends javax.swing.JFrame {

    private JPanel currentPanel;
    public Client client;
    public Player player;
    
    /**
     * Creates new form ApplicationView
     */
    public ApplicationView() throws IOException {
        super("Impiccato");

        //JPanel panel = new JPanel();
        initComponents();
        //getContentPane().add(panel);
        JPanel panel = new HomePanel(this);
        panel.setBounds(0, 0, 400, 300);
        this.currentPanel = panel;
        this.getContentPane().add(panel);
        this.setVisible(true);
        
        //this.client = new Client();
    }
   
    public void changePanel(JPanel panel){
        if(panel instanceof CreateGamePanel){
            panel = new CreateGamePanel(this);
        }else if(panel instanceof HomePanel){
            panel = new HomePanel(this);
        }else if(panel instanceof FinalPanel){
            panel = new FinalPanel(this);
        }else if(panel instanceof GamePanel){
            panel = new GamePanel(this);
        }else if(panel instanceof HomePanel){
            panel = new HomePanel(this);
        }else if(panel instanceof SettingsPanel){
            panel = new SettingsPanel(this);
        }
        panel.setBounds(0, 0, 400, 300);
        this.getContentPane().remove(this.currentPanel);
        this.getContentPane().add(panel);
        this.currentPanel = panel;
        
        this.invalidate();
        this.validate();
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ApplicationView();
                } catch (IOException ex) {
                    
                     Logger.getLogger(ApplicationView.class.getName()).log(Level.SEVERE, null, ex);
                     System.out.println("unable to start the application");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
